resolver: lts-8.16

packages:
  - # purescript
    location: '../purescript'
  - # purify
    location: '../purify'
    extra-dep: no

extra-deps:
  - pipes-http-1.0.5
  - prettyprinter-1
  - prettyprinter-ansi-terminal-1
