resolver: lts-6.18
packages:
- location:
    git: https://github.com/purescript/purescript.git
    commit: 2cad87835dbf8c9dba2ad810b32a97579ec52af6
- location:
    git: https://github.com/chrisdone/purify.git
    commit: a0e7b77286bc4ff30c11a338661f0751de398c65
